### ISSUE TITLE
how it work sc32ph.py

### ISSUE THREAD

**Issue by bosby74** [marcelobianchi/sc3tools#1]
Hi Marcelo and all,
 I'm an sc3 user and I'm trying to convert xml file to hypoDD format using the tool sc32ph.py. I've created the "Inventory.xml" file using the tool backup-sc3.sh and then I tried to convert file format using

python ~/seiscomp3/tools/sc3tools-hacks/sc32ph.py --inventory="Inventory.xml" --stations="station.hdd" --events="events.hdd"

putting the output in two files "events.hdd" and "stations.hdd". As results however I obtained these lines 

Warning, removing empty station file 'station.hdd'
Warning, removing empty event file 'events.hdd'

and none of the files I have indicated are created.  Unfortunately I'm not a good python user so I don't know exactly when I'm wrong, or if the code doesn't work as I expected...any idea? 

Thanks, SImone

**Comment by marcelobianchi** [comment]
Hi Simone, 

OK, You need to have also the input events xml file in the program arguments. In the program help it says:

```
Usage: sc32ph.py [options] <files>
```

So you should pass in the <files>

Just try:

```
python ~/seiscomp3/tools/sc3tools-hacks/sc32ph.py --inventory="Inventory.xml" --stations="station.hdd" --events="events.hdd" gfz*.xml
```

just make sure that gfz*.xml matches your events XML filenames. Your events should have also been dumped by the backup-sc3.sh

just let me know if things get wrong again, and please double check since I am the only one that used this tool and not extensively.

**Comment by bosby74** [comment]
Dear Marcelo, 
 yes, it's work, thank you!!

Simone

**Comment by bosby74** [comment]
Ok Marcelo,
 another problem...I saw that the sc32ph.py script doesn't work for several xml files created with the backup-sc3.sh script. For some of these xml I found this error

Processing event DY2005yndsfa (DY2005yndsfa.xml.tocheck)
Traceback (most recent call last):
  File "/home/simone/seiscomp3/tools/sc3tools-master/sc32ph.py", line 396, in <module>
    ev = datafromxml(f)
  File "/home/simone/seiscomp3/tools/sc3tools-master/sc32ph.py", line 303, in datafromxml
    ez  = ori.depth().uncertainty()
  File "/home/simone/seiscomp3/lib/python/seiscomp3/DataModel.py", line 1688, in uncertainty
    def uncertainty(self): return _DataModel.RealQuantity_uncertainty(self)
seiscomp3.Core.ValueException: RealQuantity.uncertainty is not set

...any idea about the reason for that??
Thank you in advance, one more time 
Simone
SImone


I found this kind of error when

**Comment by marcelobianchi** [comment]
OK, this is because I try to find the vertical error from SC3 but some origins don't have this set. Please pull again the code and see if the issue is fixed.
Marcelo

**Comment by bosby74** [comment]
Dear Marcelo,
 now the problem seem to be the Magnitude that for some xml is not set...

Processing event DY2015wxljvn (DY2015wxljvn.xml)
 No magnitude (DY2015wxljvn.xml)
Traceback (most recent call last):
  File "/home/simone/seiscomp3/tools/sc3tools-master/sc32ph.py", line 399, in <module>
    ev = datafromxml(f)
  File "/home/simone/seiscomp3/tools/sc3tools-master/sc32ph.py", line 302, in datafromxml
    eh  = math.sqrt(math.pow(ori.latitude().uncertainty(), 2)  + math.pow(ori.longitude().uncertainty(), 2))
  File "/home/simone/seiscomp3/lib/python/seiscomp3/DataModel.py", line 1688, in uncertainty
    def uncertainty(self): return _DataModel.RealQuantity_uncertainty(self)
seiscomp3.Core.ValueException: RealQuantity.uncertainty is not set

SImone

**Comment by marcelobianchi** [comment]
Well, I think it was a similar issue but for the horizontal uncertainty. I just made the same as the other, this should solve the issue.

**Comment by bosby74** [comment]
Dear Marcelo,
 tested and now it works...
Thank,
SImone
